const GHProfileData = {
  login: 'KirKol94',
  id: 83208995,
  node_id: 'MDQ6VXNlcjgzMjA4OTk1',
  avatar_url: 'https://avatars.githubusercontent.com/u/83208995?v=4',
  gravatar_id: '',
  url: 'https://api.github.com/users/KirKol94',
  html_url: 'https://github.com/KirKol94',
  followers_url: 'https://api.github.com/users/KirKol94/followers',
  following_url: 'https://api.github.com/users/KirKol94/following{/other_user}',
  gists_url: 'https://api.github.com/users/KirKol94/gists{/gist_id}',
  starred_url: 'https://api.github.com/users/KirKol94/starred{/owner}{/repo}',
  subscriptions_url: 'https://api.github.com/users/KirKol94/subscriptions',
  organizations_url: 'https://api.github.com/users/KirKol94/orgs',
  repos_url: 'https://api.github.com/users/KirKol94/repos',
  events_url: 'https://api.github.com/users/KirKol94/events{/privacy}',
  received_events_url: 'https://api.github.com/users/KirKol94/received_events',
  type: 'User',
  site_admin: false,
  name: 'Kirill Kolchanov',
  company: null,
  blog: 'kirkol94@ya.ru',
  location: 'Russia',
  email: null,
  hireable: null,
  bio: 'Front-end developer\r\nhtml, css, js, ts, react, redux and more',
  twitter_username: null,
  public_repos: 7,
  public_gists: 0,
  followers: 3,
  following: 2,
  created_at: '2021-04-26T08:03:50Z',
  updated_at: '2024-04-07T13:41:06Z',
}

export type GHProfile = typeof GHProfileData
