const GHRepositoryData = {
  id: 744912076,
  node_id: 'R_kgDOLGZ0zA',
  name: 'crm',
  full_name: 'KirKol94/crm',
  private: false,
  owner: {
    login: 'KirKol94',
    id: 83208995,
    node_id: 'MDQ6VXNlcjgzMjA4OTk1',
    avatar_url: 'https://avatars.githubusercontent.com/u/83208995?v=4',
    gravatar_id: '',
    url: 'https://api.github.com/users/KirKol94',
    html_url: 'https://github.com/KirKol94',
    followers_url: 'https://api.github.com/users/KirKol94/followers',
    following_url: 'https://api.github.com/users/KirKol94/following{/other_user}',
    gists_url: 'https://api.github.com/users/KirKol94/gists{/gist_id}',
    starred_url: 'https://api.github.com/users/KirKol94/starred{/owner}{/repo}',
    subscriptions_url: 'https://api.github.com/users/KirKol94/subscriptions',
    organizations_url: 'https://api.github.com/users/KirKol94/orgs',
    repos_url: 'https://api.github.com/users/KirKol94/repos',
    events_url: 'https://api.github.com/users/KirKol94/events{/privacy}',
    received_events_url: 'https://api.github.com/users/KirKol94/received_events',
    type: 'User',
    site_admin: false,
  },
  html_url: 'https://github.com/KirKol94/crm',
  description: null,
  fork: false,
  url: 'https://api.github.com/repos/KirKol94/crm',
  forks_url: 'https://api.github.com/repos/KirKol94/crm/forks',
  keys_url: 'https://api.github.com/repos/KirKol94/crm/keys{/key_id}',
  collaborators_url: 'https://api.github.com/repos/KirKol94/crm/collaborators{/collaborator}',
  teams_url: 'https://api.github.com/repos/KirKol94/crm/teams',
  hooks_url: 'https://api.github.com/repos/KirKol94/crm/hooks',
  issue_events_url: 'https://api.github.com/repos/KirKol94/crm/issues/events{/number}',
  events_url: 'https://api.github.com/repos/KirKol94/crm/events',
  assignees_url: 'https://api.github.com/repos/KirKol94/crm/assignees{/user}',
  branches_url: 'https://api.github.com/repos/KirKol94/crm/branches{/branch}',
  tags_url: 'https://api.github.com/repos/KirKol94/crm/tags',
  blobs_url: 'https://api.github.com/repos/KirKol94/crm/git/blobs{/sha}',
  git_tags_url: 'https://api.github.com/repos/KirKol94/crm/git/tags{/sha}',
  git_refs_url: 'https://api.github.com/repos/KirKol94/crm/git/refs{/sha}',
  trees_url: 'https://api.github.com/repos/KirKol94/crm/git/trees{/sha}',
  statuses_url: 'https://api.github.com/repos/KirKol94/crm/statuses/{sha}',
  languages_url: 'https://api.github.com/repos/KirKol94/crm/languages',
  stargazers_url: 'https://api.github.com/repos/KirKol94/crm/stargazers',
  contributors_url: 'https://api.github.com/repos/KirKol94/crm/contributors',
  subscribers_url: 'https://api.github.com/repos/KirKol94/crm/subscribers',
  subscription_url: 'https://api.github.com/repos/KirKol94/crm/subscription',
  commits_url: 'https://api.github.com/repos/KirKol94/crm/commits{/sha}',
  git_commits_url: 'https://api.github.com/repos/KirKol94/crm/git/commits{/sha}',
  comments_url: 'https://api.github.com/repos/KirKol94/crm/comments{/number}',
  issue_comment_url: 'https://api.github.com/repos/KirKol94/crm/issues/comments{/number}',
  contents_url: 'https://api.github.com/repos/KirKol94/crm/contents/{+path}',
  compare_url: 'https://api.github.com/repos/KirKol94/crm/compare/{base}...{head}',
  merges_url: 'https://api.github.com/repos/KirKol94/crm/merges',
  archive_url: 'https://api.github.com/repos/KirKol94/crm/{archive_format}{/ref}',
  downloads_url: 'https://api.github.com/repos/KirKol94/crm/downloads',
  issues_url: 'https://api.github.com/repos/KirKol94/crm/issues{/number}',
  pulls_url: 'https://api.github.com/repos/KirKol94/crm/pulls{/number}',
  milestones_url: 'https://api.github.com/repos/KirKol94/crm/milestones{/number}',
  notifications_url: 'https://api.github.com/repos/KirKol94/crm/notifications{?since,all,participating}',
  labels_url: 'https://api.github.com/repos/KirKol94/crm/labels{/name}',
  releases_url: 'https://api.github.com/repos/KirKol94/crm/releases{/id}',
  deployments_url: 'https://api.github.com/repos/KirKol94/crm/deployments',
  created_at: '2024-01-18T09:02:37Z',
  updated_at: '2024-03-25T18:20:42Z',
  pushed_at: '2024-04-04T13:36:55Z',
  git_url: 'git://github.com/KirKol94/crm.git',
  ssh_url: 'git@github.com:KirKol94/crm.git',
  clone_url: 'https://github.com/KirKol94/crm.git',
  svn_url: 'https://github.com/KirKol94/crm',
  homepage: 'http://45.147.176.25:5173/',
  size: 1432,
  stargazers_count: 1,
  watchers_count: 1,
  language: 'TypeScript',
  has_issues: true,
  has_projects: true,
  has_downloads: true,
  has_wiki: false,
  has_pages: false,
  has_discussions: false,
  forks_count: 0,
  mirror_url: null,
  archived: false,
  disabled: false,
  open_issues_count: 9,
  license: null,
  allow_forking: true,
  is_template: false,
  web_commit_signoff_required: false,
  topics: [
    'eslint',
    'express',
    'fsd',
    'jwt',
    'node',
    'prettier',
    'react',
    'redux-toolkit',
    'rtk-query',
    'scss',
    'sqlite3',
    'stylelint',
    'swagger',
    'typescript',
    'vite',
  ],
  visibility: 'public',
  forks: 0,
  open_issues: 9,
  watchers: 1,
  default_branch: 'master',
}

export type GHRepository = typeof GHRepositoryData
